/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    ApplicationBody: typeof import('./src/components/ApplicationBody.vue')['default']
    AppMain: typeof import('./src/components/AppMain.vue')['default']
    CustomInput: typeof import('./src/components/CustomInput.vue')['default']
    JobEdit: typeof import('./src/components/JobEdit.vue')['default']
    Jobs: typeof import('./src/components/Jobs.vue')['default']
    JobView: typeof import('./src/components/JobView.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
